/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.VIEWS;

import br.com.DAO.EquipsDAO;
import br.com.DAO.UsersDAO;
import br.com.DTO.EquipDTO;
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class NovoEquip extends javax.swing.JInternalFrame {

    
  

    // Método para acessar o JComboBox LabPertencente
    public JComboBox<String> getLabPertencente() {
        return cbLPertencente;
    }
    /**
     * Creates new form NovoEquip
     */
    public NovoEquip() {
        initComponents();
         chamarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnRegisEquip = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeEquip = new javax.swing.JTextField();
        txtObs = new javax.swing.JTextField();
        cbTipoEquip = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbLPertencente = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setTitle("Novo Equipamento");

        jPanel1.setBackground(new java.awt.Color(250, 239, 218));

        jPanel2.setBackground(new java.awt.Color(22, 33, 41));

        btnRegisEquip.setBackground(new java.awt.Color(22, 33, 41));
        btnRegisEquip.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisEquip.setText("Registrar Equipamento");
        btnRegisEquip.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegisEquip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisEquipActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Equipsa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegisEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegisEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(75, 75, 75));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(22, 33, 41));
        jLabel2.setText("Tipo");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 33, 41));
        jLabel3.setText("Status");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 33, 41));
        jLabel4.setText("Lab. Pertencente");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(22, 33, 41));
        jLabel5.setText("Observações");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(22, 33, 41));
        jLabel6.setText("Registro Equipamentos");

        txtNomeEquip.setBackground(new java.awt.Color(22, 33, 41));
        txtNomeEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNomeEquip.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeEquip.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtObs.setBackground(new java.awt.Color(22, 33, 41));
        txtObs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtObs.setForeground(new java.awt.Color(255, 255, 255));
        txtObs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbTipoEquip.setBackground(new java.awt.Color(22, 33, 41));
        cbTipoEquip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbTipoEquip.setForeground(new java.awt.Color(255, 255, 255));
        cbTipoEquip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "Notebook", "Mouse", "Teclado", "Fonte", "Cabo", "HD", "SSD", "RAM", "Monitor" }));
        cbTipoEquip.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbTipoEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoEquipActionPerformed(evt);
            }
        });

        cbStatus.setBackground(new java.awt.Color(22, 33, 41));
        cbStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbStatus.setForeground(new java.awt.Color(255, 255, 255));
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em uso", "Em manutenção", "Fora de uso" }));
        cbStatus.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(22, 33, 41));
        jLabel7.setText("Identificação");

        cbLPertencente.setBackground(new java.awt.Color(22, 33, 41));
        cbLPertencente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbLPertencente.setForeground(new java.awt.Color(255, 255, 255));
        cbLPertencente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem Laboratório" }));
        cbLPertencente.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cbLPertencente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLPertencenteActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(250, 239, 218));
        jSeparator1.setForeground(new java.awt.Color(239, 224, 194));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 224, 194), 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNomeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(cbTipoEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbLPertencente, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLPertencente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoEquipActionPerformed

    private void cbLPertencenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLPertencenteActionPerformed
       
    }//GEN-LAST:event_cbLPertencenteActionPerformed

    private void btnRegisEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisEquipActionPerformed
        String nome = txtNomeEquip.getText();
        String tipo = cbTipoEquip.getSelectedItem().toString();
        String status = cbStatus.getSelectedItem().toString();
        String lp = cbLPertencente.getSelectedItem().toString();
        String obs = txtObs.getText();

        EquipDTO DTO = new EquipDTO();
          DTO.setIdentificacao(nome);
          DTO.setTipoEquipamento(tipo);
          DTO. setStatus(status);
          DTO.setLabPertencente(lp);
          DTO.setObservacao(obs);

        EquipsDAO DAo = new EquipsDAO();
        DAo.NovoEquip(DTO);
    }//GEN-LAST:event_btnRegisEquipActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisEquip;
    public static javax.swing.JComboBox<String> cbLPertencente;
    public static javax.swing.JComboBox<String> cbStatus;
    public static javax.swing.JComboBox<String> cbTipoEquip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField txtNomeEquip;
    public static javax.swing.JTextField txtObs;
    // End of variables declaration//GEN-END:variables

public static void chamarDados() {
        EquipsDAO maqDAO = new EquipsDAO();
        ResultSet rs = maqDAO.listarLabins();
        try {
        while (rs.next()) {
            cbLPertencente.addItem(rs.getString(1));
        }
    } catch (SQLException erro) {
        JOptionPane.showMessageDialog(null, "hum2"+ erro.getMessage());
    }
}
}

