/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.VIEWS;

import br.com.DTO.UsuariosDTO;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        String nomeUsuario = UsuariosDTO.usuarioLogado.getNomeUsu();

        // Exibindo o nome do usuário em um JLabel
        lblNomeUsuario.setText("Bem-vindo, " + nomeUsuario);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblNomeUsuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ImageIcon icona = new ImageIcon(getClass().getResource("/img/bem-te-vi-desk"
            + ".jpg"));
    Image img = icona.getImage();
    Desktop = new javax.swing.JDesktopPane(){
        public void paintComponent(Graphics g){

            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }

    }

    ;
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    mnLab = new javax.swing.JMenuItem();
    mnEquip = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    mnGerLabs = new javax.swing.JMenuItem();
    mnGerEquips = new javax.swing.JMenuItem();
    mnGerUsers = new javax.swing.JMenuItem();
    mnManun = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Bem-te-vi! Principal");

    jPanel1.setBackground(new java.awt.Color(255, 250, 206));
    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jPanel2.setBackground(new java.awt.Color(75, 75, 75));
    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bem-tE-vi-logO.png"))); // NOI18N

    jLabel3.setBackground(new java.awt.Color(204, 204, 204));
    jLabel3.setFont(new java.awt.Font("Artifakt Element Black", 1, 24)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("BEM-TE-VI!");

    jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 211, 0));
    jLabel4.setText("Gerenciador de Hardware");

    jPanel5.setBackground(new java.awt.Color(75, 75, 75));
    jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

    lblNomeUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    lblNomeUsuario.setForeground(new java.awt.Color(204, 204, 204));
    lblNomeUsuario.setText("Bem vindo");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblNomeUsuario)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addContainerGap(88, Short.MAX_VALUE)
            .addComponent(lblNomeUsuario)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap(109, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addGap(79, 79, 79))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addGap(117, 117, 117))))
        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    jPanel3.setBackground(new java.awt.Color(255, 255, 236));
    jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 75, 75), 3, true));

    jLabel1.setBackground(new java.awt.Color(102, 102, 102));
    jLabel1.setFont(new java.awt.Font("Artifakt Element Black", 1, 48)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 211, 0));
    jLabel1.setText("PRINCIPAL");

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home-de-bird.png"))); // NOI18N

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addGap(15, 15, 15))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5)
            .addGap(19, 19, 19))
    );

    jPanel4.setBackground(new java.awt.Color(255, 255, 236));
    jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 75, 75), 3, true));

    javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
    Desktop.setLayout(DesktopLayout);
    DesktopLayout.setHorizontalGroup(
        DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    DesktopLayout.setVerticalGroup(
        DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 429, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(Desktop)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(Desktop)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
    jMenuBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

    jMenu1.setText("Novo");
    jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    mnLab.setText("Laboratório");
    mnLab.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnLabActionPerformed(evt);
        }
    });
    jMenu1.add(mnLab);

    mnEquip.setText("Equipamento");
    mnEquip.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnEquipActionPerformed(evt);
        }
    });
    jMenu1.add(mnEquip);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Gerenciar");
    jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    mnGerLabs.setText("Laboratórios");
    mnGerLabs.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnGerLabsActionPerformed(evt);
        }
    });
    jMenu2.add(mnGerLabs);

    mnGerEquips.setText("Equipamentos");
    mnGerEquips.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnGerEquipsActionPerformed(evt);
        }
    });
    jMenu2.add(mnGerEquips);

    mnGerUsers.setText("Usuários");
    mnGerUsers.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnGerUsersActionPerformed(evt);
        }
    });
    jMenu2.add(mnGerUsers);

    mnManun.setText("Manutenções");
    mnManun.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            mnManunActionPerformed(evt);
        }
    });
    jMenu2.add(mnManun);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLabActionPerformed
        if ("Administrador".equals(UsuariosDTO.usuarioLogado.getTipoUsu()) || "Técnico".equals(UsuariosDTO.usuarioLogado.getTipoUsu())) {

            NovoLab newlab = new NovoLab();
            newlab.setVisible(true);
            Desktop.add(newlab);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela!");
        }

    }//GEN-LAST:event_mnLabActionPerformed

    private void mnEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEquipActionPerformed
        if ("Administrador".equals(UsuariosDTO.usuarioLogado.getTipoUsu()) || "Técnico".equals(UsuariosDTO.usuarioLogado.getTipoUsu())) {
            NovoEquip newEquip = new NovoEquip();
            newEquip.setVisible(true);
            Desktop.add(newEquip);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela!");
        }
    }//GEN-LAST:event_mnEquipActionPerformed

    private void mnGerUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerUsersActionPerformed

        if ("Administrador".equals(UsuariosDTO.usuarioLogado.getTipoUsu())) {
            GerUsers ngu = new GerUsers();
            ngu.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela!");
        }
    }//GEN-LAST:event_mnGerUsersActionPerformed

    private void mnGerLabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerLabsActionPerformed
        if ("Administrador".equals(UsuariosDTO.usuarioLogado.getTipoUsu()) || "Técnico".equals(UsuariosDTO.usuarioLogado.getTipoUsu())) {
            GerLabs labs = new GerLabs();
            labs.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela!");
        }
    }//GEN-LAST:event_mnGerLabsActionPerformed

    private void mnGerEquipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerEquipsActionPerformed
        if ("Administrador".equals(UsuariosDTO.usuarioLogado.getTipoUsu()) || "Técnico".equals(UsuariosDTO.usuarioLogado.getTipoUsu())) {
            GerEquips equips = new GerEquips();
            equips.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela!");
        }
    }//GEN-LAST:event_mnGerEquipsActionPerformed

    private void mnManunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnManunActionPerformed

        GerManuten maq = new GerManuten();
        maq.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_mnManunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JMenuItem mnEquip;
    private javax.swing.JMenuItem mnGerEquips;
    private javax.swing.JMenuItem mnGerLabs;
    private javax.swing.JMenuItem mnGerUsers;
    private javax.swing.JMenuItem mnLab;
    private javax.swing.JMenuItem mnManun;
    // End of variables declaration//GEN-END:variables
}
